import Foundation

struct AffirmationData {
    static let englishAffirmations = [
        "You are safe.",
        "Your body is completely relaxed.",
        "Let go of all the tension in your muscles.",
        "You are surrounded by peace and calm.",
        "It is safe to let go now.",
        "Drift deeper and deeper into relaxation.",
        "Your mind is quiet and still.",
        "Every breath takes you deeper into sleep.",
        "There is nothing you need to do right now.",
        "You are loved and protected.",
        "Feel the heaviness in your body.",
        "Your thoughts are fading away like clouds.",
        "Tomorrow is a new day.",
        "You deserve deep, restorative sleep.",
        "Release all worries from your mind.",
        "You are grounded and secure.",
        "Your breathing is slow and steady.",
        "Feel the warmth of your blanket.",
        "Allow yourself to surrender to sleep.",
        "You are exactly where you need to be.",
        "Every exhale releases stress.",
        "Your eyes are heavy.",
        "Your heart beats with a calm rhythm.",
        "You are entering a deep state of rest.",
        "The world outside is fading.",
        "You have done enough for today.",
        "Peace flows through your entire body.",
        "Your muscles are melting into the bed.",
        "You are calm, comfortable, and content.",
        "Sleep comes easily and naturally."
    ]

    static let germanAffirmations = [
        "Du bist in Sicherheit.",
        "Dein Körper ist vollkommen entspannt.",
        "Lass alle Spannung in deinen Muskeln los.",
        "Du bist von Frieden und Ruhe umgeben.",
        "Es ist sicher, jetzt loszulassen.",
        "Gleite tiefer und tiefer in die Entspannung.",
        "Dein Geist ist still und ruhig.",
        "Jeder Atemzug bringt dich tiefer in den Schlaf.",
        "Es gibt jetzt nichts, was du tun musst.",
        "Du wirst geliebt und bist beschützt.",
        "Spüre die Schwere in deinem Körper.",
        "Deine Gedanken ziehen vorbei wie Wolken.",
        "Morgen ist ein neuer Tag.",
        "Du verdienst tiefen, erholsamen Schlaf.",
        "Lass alle Sorgen aus deinem Geist entweichen.",
        "Du bist geerdet und sicher.",
        "Deine Atmung ist langsam und gleichmäßig.",
        "Spüre die Wärme deiner Decke.",
        "Erlaube dir, dich dem Schlaf hinzugeben.",
        "Du bist genau dort, wo du sein sollst.",
        "Jedes Ausatmen lässt Stress entweichen.",
        "Deine Augen sind schwer.",
        "Dein Herz schlägt in einem ruhigen Rhythmus.",
        "Du betrittst einen tiefen Zustand der Ruhe.",
        "Die Welt draußen verblasst.",
        "Du hast heute genug getan.",
        "Frieden strömt durch deinen ganzen Körper.",
        "Deine Muskeln schmelzen in das Bett.",
        "Du bist ruhig, bequem und zufrieden.",
        "Der Schlaf kommt leicht und natürlich."
    ]
}
